### ISSUE TITLE
No spawning trains

### ISSUE THREAD

**Issue by kevintransp** [VenomXNL/XNL-FiveM-Trains-U3#1]
Good day sire,
Really like this recourse to work but no trains are spawning, no errors nothing.

Any sugestions?

**Comment by OreoFR** [comment]
me too

**Comment by VenomXNL** [comment]
This issue is known but unfortunately we can't figure out the exact reason why this happens. For us for example (whom have created ALL scripts and gamemodes (plus framework) from scratch) it works fine except for the point where trains sometimes de-spawn randomly (even when near or on them). While for others they don't spawn at all and it often conflicts with scripts like "real AI" or "BetterAI" for example. We are looking into it but has low priority due to family circumstances and this "just being an addon part" of our (own server/) gamemode which is still in development. We SUSPECT (not sure though!) that a native function or handler of the game 'messes with' the trains and "Mission trains" (which is the function/native used to spawn them). Multiple others are also in spare time trying to figure out the de-spawning or not spawning at all. More about this can often be found at the FiveM forum topic about this release :)

If we find the solution (and one that works properly on long-term) i will definitely update the script :)

**Comment by Daandeve** [comment]
Still not working at this time...
Or am I doing something wrong?

**Comment by IOxeOfficial** [comment]
I don't get trains. Do you need a dependency or something?

**Comment by VenomXNL** [comment]
Unfortunately there are issues known which don't appear to happen on a 100% "clean/empty server", but lots of other scripts (which trigger internal game functions for example) will cause this issue.

as posted in my reply/comment on 28 Apr 2019, this is unfortunately still valid.

I myself however have **completely** stopped developing FiveM mods and same goes for working on them (as updating) due to time limitations.

If anyone wants to pick it up from here, they are welcome to do so :)

**Comment by TheNickoos** [comment]
Its just simply not working on OneSync server.
You need to remove hardcap system in the code and rebuilt it ;)

**Comment by VenomXNL** [comment]
> 
> 
> Its just simply not working on OneSync server.
> You need to remove hardcap system in the code and rebuilt it ;)

This is known and listed on the page itself on FiveM ;) :)

I haven't been working on this project (or ANY FiveM related project) for a long time, nor will i return to them I guess.

If you would like to fork and update it, you're more than welcome to do so :)

However it's not just a hardcap problem, there are also issues in this release which utilize the native game spawning engine which can't be used with OneSync at all.

Aside from that: That native spawning system did had issues from the start with other scripts interfering with it, and until today (as far as i know) still nobody has found the exact issues/functions which triggered the problems.

It's unfortunately not someting obvious which causes the spawn problems (but then again: I haven't worked on it for a LOOOOONGGG time haha) :)

**Comment by VenomXNL** [comment]
I will hereby close the issue (despite it not being resolved) because i'm no longer working on it, and with OneSync it's completly becoming obsolete in it's current form. 

If you would like to continue on it please fork it and rewrite it for proper use with the (much) newer versions of FiveM :)
