### ISSUE TITLE
Some people crash when the trains are turned on and join.

### ISSUE THREAD

**Issue by WoozyFace** [VenomXNL/XNL-FiveM-Trains-U3#10]
Hi there,

Some people seem to crash if the trains are turned on, and they try to join. They get this error; 
![SCRIPT_ERROR_TREINEN](https://user-images.githubusercontent.com/91032578/146673165-d3c7eae7-7b3c-4f02-bf1d-67d95ab092d8.jpg)

However, if they already have been joined, there is no issue with starting the trains! 

Did I miss something, or is this just a known bug?? 

Thanks for your time and effort to help us out.

**Comment by VenomXNL** [comment]
Hey, Sorry due to lots of stuff going on lately in regards to work, personal life and the whole covid situation I haven't had any time to check on things like these earlier, sorry for that.

I personally have stopped a while ago with (most of) my FiveM mods, scripts and servers.
However for this on it's unfortunately known that there is an **massive** issue with either FiveM or GTA V where it can/will go **horribly** wrong with the trains on several occasions.

This is mainly (my guess though) due to the game engine itself not properly syncing and passing on the 'main host' (aka the closest player) to the spawned train(s).

I have found another solution though which SEEMS to work A LOT better, and uses the 'normal GTA V/GTA:O trains' without any additional scripting required. HOWEVER this would mean that the ticket system for my train system would not work or it would need to be converted to this new method.

I MIGHT see if i can get an FiveM server up and running somewhere in the (near?) future to re-write the script again :)
It is quite simple though if you can edit any client script and insert these lines:

`Citizen.CreateThread(function()
    SwitchTrainTrack(0, true) 					-- Main train track(s) around LS and towards Sandy Shores
    SwitchTrainTrack(3, true) 					-- Metro tracks
    SetTrainTrackSpawnFrequency(0, 120000)		-- The Train spawn frequency set for the game engine
    SetTrainTrackSpawnFrequency(3, 120000)		-- The Metro spawn frequency set for the game engine
    SetRandomTrains(true)						-- Telling the game we want to use randomly spawned trains
end)`

(DISABLE MY ENTIRE SCRIPT THOUGH!) 

The trains should work as intended :)

Unfortunately I didn't had these api's/calls available (as in I didn't knew them back then or they where not even discovered/documented yet back then).

Hopefull this is useful for you for now :)
