### ISSUE TITLE
Train Doors

### ISSUE THREAD

**Issue by Meister119** [VenomXNL/XNL-FiveM-Trains-U3#13]
When I get on the train and it starts moving, the doors don't close 
![image](https://github.com/VenomXNL/XNL-FiveM-Trains-U3/assets/56088116/c9035409-e02b-4c17-9934-f786ae743591)

**Comment by VenomXNL** [comment]
I know, and it clearly states this in the readme 😄 , and on the first page of the repository why this happens (well a guess).

My script doesn't do anything in regards to controlling the trains, the doors or spawning (any of) them.

All my scripts does (in regards to the trains themselves) is activating the normal game tracks. IF I would spawn the trains while having full control over them, it will cause A LOT of issues when multiple players join.

Like for example:  duplicated trains, trains suddenly despawning, or not spawning at all etc etc.
Which is why this new version is released to work around those problems by using the Native GTA train tracks.

Issue therefor closed.
