### ISSUE TITLE
Doesnt work on ONESYNC

### ISSUE THREAD

**Issue by rex2630** [VenomXNL/XNL-FiveM-Trains-U3#2]
Title says it all

**Comment by VenomXNL** [comment]
Sorry i'm not running OneSync nor plan on doing so in the near future, If anyone knows the exact reason why it doesn't (although i suspect it has to do with the train spawning system, which could be replaced with the SwitchTrainTrack function to test it, but i can't confirm this), or knows a solution to make it onesync compatible (assuming it's not a onesync option and that onesync does support the trains in their protocol at this point), please be free to fork an patch :)

**Comment by VenomXNL** [comment]
Just to clarify and make sure that others don't think it's 'resolved': IT IS NOT resolved, i just closed the issue because OneSync and the original FiveM way of using the game are COMPLETELY different.

Plus i've also decided to **completely** abandon this mod in regards of developing or updating it, this due to lack of time. So if anyone wants to pick up from here, they are free to do so (with credits where due of course).
