### ISSUE TITLE
Question about frozen trains

### ISSUE THREAD

**Issue by FurmaZ** [VenomXNL/XNL-FiveM-Trains-U3#9]
So I have a problem sometimes train wagons just stops and freeze. so when other train comes it goes throught it like nothing but it looks weird if its like 4-5 wagons frozen any idea how to fix it?

**Comment by VenomXNL** [comment]
"any idea how to fix it?" 

First of all: Sorry didn't noticed your question until now.

As for my answer: Yes and no...... ;)

This is a known problem (also stated at the release page on the FiveM forum).

I have also "abandoned" this version due to this problem, which is/was a game (engine) problem when used in combination with FiveM which is a "completly technical story" about networked entity's etc etc.


HOWEVER... I have recently made some new discovery's in the native system of the game and might actually either release a NEW version or adapt this one (although i think it will be the first option because others have also forked this version and worked on it themselves).


I would however recommend NOT to use it to prevent these network migration issues, and either wait for the new version (NOT known when i will be able to work in it though sorry), or to "just let it go for now" (not recommended though!)
